"""One non-secret command catalogue -> standalone client and C++ export helper."""
from pathlib import Path
import json
r=Path(__file__).resolve().parents[1]
data=json.loads((r/'tools/texstudio-cli-help.json').read_text(encoding='utf-8'))
for name,item in data['commands'].items():
    if 'example' not in item:
        words=['python3 texstudioctl.py --session texstudio-session.json',name]
        for key,value in item['request'].items():
            if key!='command': words += ['--'+key,str(value)]
        item['example']=' '.join(words)
payload=json.dumps(data,ensure_ascii=False,separators=(',',':'))
p=r/'tools/texstudioctl.py';s=p.read_text(encoding='utf-8')
start='# BEGIN GENERATED HELP';end='# END GENERATED HELP'
block=start+'\nCLI_HELP = json.loads('+repr(payload)+')\n'+end
if start in s:
    a=s.index(start);b=s.index(end,a)+len(end);s=s[:a]+block+s[b:]
else:s=s.replace('from pathlib import Path','from pathlib import Path\n\n'+block)
p.write_text(s,encoding='utf-8')
header='''// Generated by build-support/generate-cli-help.py; edit tools/texstudio-cli-help.json.
#pragma once
#include <QJsonDocument>
#include <QJsonObject>
inline QJsonObject harmonyCliHelp() {
    return QJsonDocument::fromJson(QByteArray(R"CLIHELP('''+payload+''')CLIHELP")).object();
}
'''
(r/'texstudio-harmony/third_party/texstudio/src/harmonyclihelp.h').write_text(header,encoding='utf-8')
print('Generated standalone CLI help and application export catalogue')
