"""Local synthetic OpenAI-compatible tool/SSE fixture; never logs headers or prompts."""
import json,time
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
class Handler(BaseHTTPRequestHandler):
    def log_message(self,*args): pass
    def do_POST(self):
        data=json.loads(self.rfile.read(int(self.headers['Content-Length'])))
        messages=data['messages']; last=messages[-1]; task=next((m['content'] for m in reversed(messages) if m['role']=='user'),'')
        name=None;args={};delay=0
        if last['role']=='tool':
            result=json.loads(last['content'])
            if last.get('name')=='read_file' and 'revision' in result and 'before' in result.get('text',''):
                name='replace_text';args={'path':'a.tex','revision':result['revision'],'old_text':'before','new_text':'after'}
            else: text='工具测试完成：'+json.dumps(result,ensure_ascii=False)
        elif 'cancel' in task:
            name='create_file';args={'path':'cancelled.tex','text':'Must not exist after cancellation'};delay=8
        elif 'create' in task:
            name='create_file';args={'path':'generated.tex','text':'% generated by synthetic tool test\nHello.\n'}
        elif 'unsafe' in task:
            name='read_file';args={'path':'../outside.tex'}
        elif 'edit' in task:
            name='read_file';args={'path':'a.tex'}
        else:text='**中文回复**\n\n简洁侧栏测试。\n```latex\n\\section{示例}\n```'
        self.send_response(200);self.send_header('Content-Type','text/event-stream');self.end_headers()
        if name: delta={'tool_calls':[{'index':0,'id':'call_fixture_'+str(time.time_ns()),'type':'function','function':{'name':name,'arguments':json.dumps(args,ensure_ascii=False)}}]}
        else:delta={'content':text}
        event=('data: '+json.dumps({'choices':[{'delta':delta}]},ensure_ascii=False)+'\r\n\r\n').encode()
        try:
            for i in range(0,len(event),11):self.wfile.write(event[i:i+11]);self.wfile.flush();time.sleep(.003)
            time.sleep(delay);self.wfile.write(b'data: [DONE]\n\n');self.wfile.flush()
        except (BrokenPipeError,ConnectionResetError):pass
print('Workbench32 fixture listening on loopback :18833',flush=True)
ThreadingHTTPServer(('127.0.0.1',18833),Handler).serve_forever()
