"""Single release source; generate only non-secret app/version files."""
import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def load():
    data = json.loads((ROOT / "release.json").read_text(encoding="utf-8"))
    if not re.fullmatch(r"\d+\.\d+\.\d+", data["version"]):
        raise ValueError("Invalid release version")
    if not re.fullmatch(r"\d+\.\d+\.\d+", data.get("runtimeVersion", data["version"])):
        raise ValueError("Invalid runtime version")
    if type(data["versionCode"]) is not int or data["versionCode"] <= 0:
        raise ValueError("Invalid versionCode")
    return data


def generated(data):
    header = ROOT / "third_party/texstudio/src/harmonyRelease.h"
    yield header, ('// Generated by scripts/release_config.py; edit release.json.\n'
                   '#pragma once\n#define HARMONY_TEX_VERSION "' + data["version"] + '"\n'
                   '#define HARMONY_RUNTIME_VERSION "' + data.get("runtimeVersion", data["version"]) + '"\n'
                   '#define HARMONY_TEX_COMPATIBILITY ' + json.dumps(data["compatibilityId"]) + '\n')
    app = ROOT / "texstudio_harmony/AppScope/app.json5"
    content = app.read_text(encoding="utf-8")
    content = re.sub(r'("versionCode"\s*:\s*)\d+', lambda m: m[1] + str(data["versionCode"]), content)
    content = re.sub(r'("versionName"\s*:\s*)"[^"]*"', lambda m: m[1] + json.dumps(data["version"]), content)
    yield app, content


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--field")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    data = load()
    if args.field:
        print(data[args.field])
    else:
        stale = []
        for path, content in generated(data):
            if args.write:
                path.write_text(content, encoding="utf-8", newline="\n")
            elif not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        if stale:
            sys.exit("Stale release files: " + ", ".join(stale))
        print("Release configuration " + data["version"] + ": " + ("generated" if args.write else "consistent"))
